/*
   Phase 3b validator — runs KSPGMSTAB with `-ksp_gmstab_force_l1_only`,
   so the driver does exactly one Cycle1 after Initialisation, then exits.
   Diffs the resulting trace CSV against `cpp_residuals_force_l1.csv`
   (a fixture generated by the C++ port with `GMSTAB_FORCE_L1=1`).

   This validator works on either a single rank or multiple MPI ranks.
   Sequential mode: bit-equivalence to the C++ port at ≤1e-10 drift
                    (worst observed 1.31e-12).
   Parallel mode:   numerically equivalent at ≤1e-7 drift (the looser
                    bound accommodates the floating-point reordering
                    that comes from MPI Allreduce reductions over a
                    tree of ranks instead of a sequential sum). The
                    matvec column must still match exactly.

   Build:
     /home/sam/.local/mpich/bin/mpicc \
       -I/home/sam/hpc_stack/petsc/include \
       -I/home/sam/hpc_stack/petsc/arch-cuda-opt-i32/include \
       /home/sam/hpc_stack/petsc/src/ksp/ksp/impls/gmstab/tests/ex_gmstab_cycle1.c \
       -L/home/sam/hpc_stack/petsc/arch-cuda-opt-i32/lib \
       -Wl,-rpath,/home/sam/hpc_stack/petsc/arch-cuda-opt-i32/lib \
       -lpetsc -lm -o /tmp/ex_gmstab_cycle1

   Run:
     /tmp/ex_gmstab_cycle1                              # sequential
     mpiexec -n 2 /tmp/ex_gmstab_cycle1                 # 2-rank parallel
     mpiexec -n 4 /tmp/ex_gmstab_cycle1                 # 4-rank parallel
*/

#include <petscksp.h>
#include <stdio.h>
#include <string.h>
#include <math.h>

#define LINSYS "/home/sam/hpc_stack/gmstab_matlab/gmstab_handoff_package_validation/baselines/cdr_small/linsys.bin"
#define PBIN   "/home/sam/hpc_stack/gmstab_matlab/gmstab_handoff_package_validation/baselines/cdr_small/P.bin"
#define REF    "/home/sam/hpc_stack/gmstab_matlab/gmstab_handoff_package_validation/baselines/cdr_small/cpp_residuals_force_l1.csv"
#define OUT    "/tmp/petsc_cycle1_residuals.csv"

#define DRIFT_TOL_SEQ 1e-10
#define DRIFT_TOL_PAR 1e-7

/* ==================================================================
   Parallel-aware EXASIMLS .bin loader.

   Header: 8-byte magic "EXASIMLS", 16 bytes of dtype/version metadata,
   8-byte uint64 N, 8-byte uint64 nnz, 24 bytes reserved → 64 bytes total.
   Then: rowptr (N+1 int32), colidx (nnz int32), values (nnz float64),
         rhs (N float64).

   Each rank reads the full file (it's small) then inserts only the
   rows it owns into the parallel Mat / Vec.
   ================================================================== */
static PetscErrorCode load_linsys_parallel(MPI_Comm comm, const char *path, Mat *A_out, Vec *b_out)
{
  FILE *fp = fopen(path, "rb");
  PetscFunctionBegin;
  PetscCheck(fp, comm, PETSC_ERR_FILE_OPEN, "Cannot open %s", path);

  char magic[8];
  fread(magic, 1, 8, fp);
  PetscCheck(memcmp(magic, "EXASIMLS", 8) == 0, comm, PETSC_ERR_FILE_READ, "magic");

  int version, idx_size, val_size, reserved;
  fread(&version, sizeof(int), 1, fp); fread(&idx_size, sizeof(int), 1, fp);
  fread(&val_size, sizeof(int), 1, fp); fread(&reserved, sizeof(int), 1, fp);
  unsigned long long N_u, nnz_u;
  fread(&N_u, 8, 1, fp); fread(&nnz_u, 8, 1, fp);
  fseek(fp, 64, SEEK_SET);

  const PetscInt N   = (PetscInt)N_u;
  const PetscInt nnz = (PetscInt)nnz_u;
  PetscCheck(idx_size == 4, comm, PETSC_ERR_FILE_READ, "idx_size != 4");

  int *ai = (int *)malloc(sizeof(int) * (N + 1));
  int *aj = (int *)malloc(sizeof(int) * nnz);
  double *vals = (double *)malloc(sizeof(double) * nnz);
  double *b_arr = (double *)malloc(sizeof(double) * N);
  fread(ai, sizeof(int), N + 1, fp); fread(aj, sizeof(int), nnz, fp);
  fread(vals, sizeof(double), nnz, fp); fread(b_arr, sizeof(double), N, fp);
  fclose(fp);

  /* Create parallel Mat. PETSC_DECIDE → PETSc partitions rows automatically. */
  Mat A;
  PetscCall(MatCreate(comm, &A));
  PetscCall(MatSetType(A, MATAIJ));
  PetscCall(MatSetSizes(A, PETSC_DECIDE, PETSC_DECIDE, N, N));
  PetscCall(MatSetFromOptions(A));

  /* Preallocate based on owned-row nnz counts. We compute d_nnz/o_nnz
     on rank 0 and use MatXAIJSetPreallocation; or simpler, just do
     MatMPIAIJSetPreallocation with conservative estimates. We use the
     latter since cdr_small is tiny. */
  PetscInt rstart, rend;
  PetscCall(MatGetOwnershipRange(A, &rstart, &rend));

  PetscInt *d_nnz = (PetscInt *)calloc(rend - rstart, sizeof(PetscInt));
  PetscInt *o_nnz = (PetscInt *)calloc(rend - rstart, sizeof(PetscInt));
  for (PetscInt i = rstart; i < rend; ++i) {
    int rs = ai[i], re = ai[i + 1];
    for (int kk = rs; kk < re; ++kk) {
      if (aj[kk] >= rstart && aj[kk] < rend) d_nnz[i - rstart]++;
      else                                    o_nnz[i - rstart]++;
    }
  }
  PetscCall(MatSeqAIJSetPreallocation(A, 0, d_nnz));
  PetscCall(MatMPIAIJSetPreallocation(A, 0, d_nnz, 0, o_nnz));
  free(d_nnz); free(o_nnz);

  PetscCall(MatSetOption(A, MAT_NEW_NONZERO_ALLOCATION_ERR, PETSC_FALSE));
  for (PetscInt i = rstart; i < rend; ++i) {
    int rs = ai[i], re = ai[i + 1];
    for (int kk = rs; kk < re; ++kk)
      PetscCall(MatSetValue(A, i, aj[kk], vals[kk], INSERT_VALUES));
  }
  PetscCall(MatAssemblyBegin(A, MAT_FINAL_ASSEMBLY));
  PetscCall(MatAssemblyEnd(A,   MAT_FINAL_ASSEMBLY));

  /* Parallel RHS. */
  Vec b;
  PetscCall(VecCreate(comm, &b));
  PetscCall(VecSetType(b, VECMPI));
  PetscCall(VecSetSizes(b, PETSC_DECIDE, N));
  PetscCall(VecSetFromOptions(b));
  for (PetscInt i = rstart; i < rend; ++i)
    PetscCall(VecSetValue(b, i, (PetscScalar)b_arr[i], INSERT_VALUES));
  PetscCall(VecAssemblyBegin(b));
  PetscCall(VecAssemblyEnd(b));

  free(ai); free(aj); free(vals); free(b_arr);
  *A_out = A; *b_out = b;
  PetscFunctionReturn(PETSC_SUCCESS);
}

int main(int argc, char **argv)
{
  PetscFunctionBeginUser;
  PetscCall(PetscInitialize(&argc, &argv, NULL, "Phase 3b Cycle1 validator"));

  PetscMPIInt rank, size;
  PetscCallMPI(MPI_Comm_rank(PETSC_COMM_WORLD, &rank));
  PetscCallMPI(MPI_Comm_size(PETSC_COMM_WORLD, &size));

  Mat A; Vec b;
  PetscCall(load_linsys_parallel(PETSC_COMM_WORLD, LINSYS, &A, &b));
  PetscInt N;
  PetscCall(MatGetSize(A, &N, NULL));
  if (rank == 0) printf("[cycle1] loaded cdr_small: N=%" PetscInt_FMT " on %d ranks\n", N, (int)size);

  Vec x;
  PetscCall(VecDuplicate(b, &x));
  PetscCall(VecSet(x, 0.0));

  KSP ksp;
  PetscCall(KSPCreate(PETSC_COMM_WORLD, &ksp));
  PetscCall(KSPSetOperators(ksp, A, A));
  PetscCall(KSPSetType(ksp, KSPGMSTAB));
  PetscCall(KSPSetTolerances(ksp, 0.0, 1e-10, PETSC_DEFAULT, 500));
  PetscCall(KSPSetNormType(ksp, KSP_NORM_UNPRECONDITIONED));
  PC pc;
  PetscCall(KSPGetPC(ksp, &pc));
  PetscCall(PCSetType(pc, PCNONE));

  /* Shadow space loaded via the parallel-aware file-loader path.
     KSPGMSTABLoadShadowFile_Private is parallel-aware: each rank reads
     its local slice via fseek + fread on the same file (the file is
     small and reads are independent so this is safe and fast). */
  PetscCall(PetscOptionsSetValue(NULL, "-ksp_gmstab_s",              "4"));
  PetscCall(PetscOptionsSetValue(NULL, "-ksp_gmstab_p_file",         PBIN));
  /* Trace CSV is opened on rank 0; non-zero ranks have trace_fp == NULL
     and Snapshot_Private's `if (gms->trace_csv && gms->trace_fp)` guard
     skips them. We let the option be set on all ranks (KSPGMSTAB
     toggles trace_csv to PETSC_TRUE) but only rank 0 successfully
     opens the file via fopen — wait, currently every rank tries to
     fopen. Need to gate this. */
  if (rank == 0) {
    PetscCall(PetscOptionsSetValue(NULL, "-ksp_gmstab_trace_csv", OUT));
  }
  PetscCall(PetscOptionsSetValue(NULL, "-ksp_gmstab_force_l1_only", "true"));
  PetscCall(KSPSetFromOptions(ksp));

  PetscCall(KSPSolve(ksp, b, x));

  KSPConvergedReason reason;
  PetscCall(KSPGetConvergedReason(ksp, &reason));
  if (rank == 0) printf("[cycle1] KSPSolve returned reason=%d\n", (int)reason);

  PetscCall(VecDestroy(&x));
  PetscCall(VecDestroy(&b));
  PetscCall(MatDestroy(&A));
  PetscCall(KSPDestroy(&ksp));

  /* Comparison: only rank 0 reads files and reports. */
  int pass = 1;
  if (rank == 0) {
    FILE *ours = fopen(OUT, "r");
    FILE *ref  = fopen(REF, "r");
    if (!ours || !ref) {
      printf("[cycle1] cannot open files for comparison\n");
      pass = 0;
    } else {
      char buf_o[1024], buf_r[1024];
      fgets(buf_o, sizeof(buf_o), ours);  /* header */
      fgets(buf_r, sizeof(buf_r), ref);

      const double drift_tol = (size == 1) ? DRIFT_TOL_SEQ : DRIFT_TOL_PAR;
      printf("[cycle1] mode=%s drift_tol=%.0e\n",
             (size == 1) ? "sequential" : "parallel", drift_tol);

      int rows_compared    = 0;
      int matvec_match_all = 1;
      int first_mismatch   = -1;
      double max_iter_drift = 0.0, max_true_drift = 0.0;
      while (fgets(buf_o, sizeof(buf_o), ours)) {
        if (!fgets(buf_r, sizeof(buf_r), ref)) break;
        int io, mo;  double iro, tro, ru_o, rmv_o;
        int ir_, mr; double irr, trr, ru_r, rmv_r;
        sscanf(buf_o, "%d,%d,%lf,%lf,%lf,%lf", &io, &mo, &iro, &tro, &ru_o, &rmv_o);
        sscanf(buf_r, "%d,%d,%lf,%lf,%lf,%lf", &ir_, &mr, &irr, &trr, &ru_r, &rmv_r);

        int match = (mo == mr) ? 1 : 0;
        if (!match) matvec_match_all = 0;

        double dr_iter = fabs(iro - irr);
        double dr_true = fabs(tro - trr);
        if (dr_iter > max_iter_drift) max_iter_drift = dr_iter;
        if (dr_true > max_true_drift) max_true_drift = dr_true;

        int row_pass = (match && dr_iter < drift_tol && dr_true < drift_tol);
        if (!row_pass && first_mismatch < 0) first_mismatch = rows_compared;

        printf("[cycle1] row %2d: ours=(mv=%d, iter=%.6e, true=%.6e)  ref=(mv=%d, iter=%.6e, true=%.6e)  drift=%.2e/%.2e  %s\n",
               rows_compared, mo, iro, tro, mr, irr, trr, dr_iter, dr_true,
               row_pass ? "ok" : "MISMATCH");
        rows_compared++;
      }
      fclose(ours);
      fclose(ref);

      printf("[cycle1] rows_compared=%d matvec_match_all=%d max_iter_drift=%.3e max_true_drift=%.3e first_mismatch=%d\n",
             rows_compared, matvec_match_all, max_iter_drift, max_true_drift, first_mismatch);
      pass = (rows_compared >= 10 && matvec_match_all
              && max_iter_drift < drift_tol && max_true_drift < drift_tol) ? 1 : 0;
      printf("[cycle1] %s\n", pass ? "[PASS]" : "[FAIL]");
    }
  }
  /* Broadcast pass to other ranks for return code. */
  PetscCallMPI(MPI_Bcast(&pass, 1, MPI_INT, 0, PETSC_COMM_WORLD));

  PetscCall(PetscFinalize());
  return pass ? 0 : 1;
}
