/*
   Phase 3d (audit pass 3) validator — multi-solve repeatability with
   the default-RNG shadow-space path.

   Identical in structure to ex_gmstab_multisolve, but DOES NOT pass
   -ksp_gmstab_p_file. The shadow space is therefore generated by
   KSPGMSTABBuildDefaultShadow_Private (PETSc's RNG path) on each
   KSPSolve call.

   What this gates that ex_gmstab_multisolve misses
   -------------------------------------------------
   The C++ port's default_shadow_space() constructs a fresh
   std::mt19937_64 from the seed on EVERY call, so two consecutive
   solves get the same P. PETSc's KSPGMSTABBuildDefaultShadow_Private
   used to create gms->prand once and never re-seed it — second solve
   would consume RNG state left over from the first and produce a
   *different* P, breaking determinism. The fix re-seeds gms->prand on
   every call. This validator exercises that path: two solves with
   default RNG must produce ‖x1 − x2‖₂ = 0 exactly.
*/

#include <petscksp.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define LINSYS  "/home/sam/hpc_stack/gmstab_matlab/gmstab_handoff_package_validation/baselines/cdr_small/linsys.bin"

#define TOLABS         1e-10
#define FINAL_RES_FUDGE 1.5

static PetscErrorCode load_linsys_parallel(MPI_Comm comm, const char *path, Mat *A_out, Vec *b_out)
{
  FILE *fp = fopen(path, "rb");
  PetscFunctionBegin;
  PetscCheck(fp, comm, PETSC_ERR_FILE_OPEN, "Cannot open %s", path);
  char magic[8];
  fread(magic, 1, 8, fp);
  PetscCheck(memcmp(magic, "EXASIMLS", 8) == 0, comm, PETSC_ERR_FILE_READ, "magic");
  int version, idx_size, val_size, reserved;
  fread(&version, sizeof(int), 1, fp); fread(&idx_size, sizeof(int), 1, fp);
  fread(&val_size, sizeof(int), 1, fp); fread(&reserved, sizeof(int), 1, fp);
  unsigned long long N_u, nnz_u;
  fread(&N_u, 8, 1, fp); fread(&nnz_u, 8, 1, fp);
  fseek(fp, 64, SEEK_SET);
  const PetscInt N   = (PetscInt)N_u;
  const PetscInt nnz = (PetscInt)nnz_u;
  PetscCheck(idx_size == 4, comm, PETSC_ERR_FILE_READ, "idx_size != 4");
  int *ai = (int *)malloc(sizeof(int) * (N + 1));
  int *aj = (int *)malloc(sizeof(int) * nnz);
  double *vals = (double *)malloc(sizeof(double) * nnz);
  double *b_arr = (double *)malloc(sizeof(double) * N);
  fread(ai, sizeof(int), N + 1, fp); fread(aj, sizeof(int), nnz, fp);
  fread(vals, sizeof(double), nnz, fp); fread(b_arr, sizeof(double), N, fp);
  fclose(fp);
  Mat A;
  PetscCall(MatCreate(comm, &A));
  PetscCall(MatSetType(A, MATAIJ));
  PetscCall(MatSetSizes(A, PETSC_DECIDE, PETSC_DECIDE, N, N));
  PetscCall(MatSetFromOptions(A));
  PetscInt rstart, rend;
  PetscCall(MatGetOwnershipRange(A, &rstart, &rend));
  PetscInt *d_nnz = (PetscInt *)calloc(rend - rstart, sizeof(PetscInt));
  PetscInt *o_nnz = (PetscInt *)calloc(rend - rstart, sizeof(PetscInt));
  for (PetscInt i = rstart; i < rend; ++i) {
    int rs = ai[i], re = ai[i + 1];
    for (int kk = rs; kk < re; ++kk) {
      if (aj[kk] >= rstart && aj[kk] < rend) d_nnz[i - rstart]++;
      else                                    o_nnz[i - rstart]++;
    }
  }
  PetscCall(MatSeqAIJSetPreallocation(A, 0, d_nnz));
  PetscCall(MatMPIAIJSetPreallocation(A, 0, d_nnz, 0, o_nnz));
  free(d_nnz); free(o_nnz);
  PetscCall(MatSetOption(A, MAT_NEW_NONZERO_ALLOCATION_ERR, PETSC_FALSE));
  for (PetscInt i = rstart; i < rend; ++i) {
    int rs = ai[i], re = ai[i + 1];
    for (int kk = rs; kk < re; ++kk)
      PetscCall(MatSetValue(A, i, aj[kk], vals[kk], INSERT_VALUES));
  }
  PetscCall(MatAssemblyBegin(A, MAT_FINAL_ASSEMBLY));
  PetscCall(MatAssemblyEnd(A,   MAT_FINAL_ASSEMBLY));
  Vec b;
  PetscCall(VecCreate(comm, &b));
  PetscCall(VecSetType(b, VECMPI));
  PetscCall(VecSetSizes(b, PETSC_DECIDE, N));
  PetscCall(VecSetFromOptions(b));
  for (PetscInt i = rstart; i < rend; ++i)
    PetscCall(VecSetValue(b, i, (PetscScalar)b_arr[i], INSERT_VALUES));
  PetscCall(VecAssemblyBegin(b));
  PetscCall(VecAssemblyEnd(b));
  free(ai); free(aj); free(vals); free(b_arr);
  *A_out = A; *b_out = b;
  PetscFunctionReturn(PETSC_SUCCESS);
}

int main(int argc, char **argv)
{
  PetscFunctionBeginUser;
  PetscCall(PetscInitialize(&argc, &argv, NULL, "Multi-solve repeatability gate (default RNG path)"));

  PetscMPIInt rank, size;
  PetscCallMPI(MPI_Comm_rank(PETSC_COMM_WORLD, &rank));
  PetscCallMPI(MPI_Comm_size(PETSC_COMM_WORLD, &size));

  Mat A; Vec b;
  PetscCall(load_linsys_parallel(PETSC_COMM_WORLD, LINSYS, &A, &b));
  PetscInt N;
  PetscCall(MatGetSize(A, &N, NULL));
  if (rank == 0) printf("[multisolve-rng] loaded cdr_small: N=%" PetscInt_FMT " on %d ranks\n", N, (int)size);

  Vec x1, x2;
  PetscCall(VecDuplicate(b, &x1));
  PetscCall(VecDuplicate(b, &x2));
  PetscCall(VecSet(x1, 0.0));
  PetscCall(VecSet(x2, 0.0));

  KSP ksp;
  PetscCall(KSPCreate(PETSC_COMM_WORLD, &ksp));
  PetscCall(KSPSetOperators(ksp, A, A));
  PetscCall(KSPSetType(ksp, KSPGMSTAB));
  PetscCall(KSPSetTolerances(ksp, 0.0, TOLABS, PETSC_DEFAULT, 2000));
  PetscCall(KSPSetNormType(ksp, KSP_NORM_UNPRECONDITIONED));
  PC pc;
  PetscCall(KSPGetPC(ksp, &pc));
  PetscCall(PCSetType(pc, PCNONE));

  PetscCall(PetscOptionsSetValue(NULL, "-ksp_gmstab_s", "4"));
  /* DELIBERATELY no -ksp_gmstab_p_file: P is generated by the default
     RNG path inside KSPGMSTABBuildDefaultShadow_Private. */
  PetscCall(KSPSetFromOptions(ksp));

  /* ---- Solve 1 ---- */
  PetscCall(KSPSolve(ksp, b, x1));
  KSPConvergedReason r1;
  PetscReal          rn1;
  PetscCall(KSPGetConvergedReason(ksp, &r1));
  PetscCall(KSPGetResidualNorm(ksp, &rn1));

  /* ---- Solve 2 (same KSP, same b, same x0=0) ---- */
  PetscCall(VecSet(x2, 0.0));
  PetscCall(KSPSolve(ksp, b, x2));
  KSPConvergedReason r2;
  PetscReal          rn2;
  PetscCall(KSPGetConvergedReason(ksp, &r2));
  PetscCall(KSPGetResidualNorm(ksp, &rn2));

  /* External residuals on the user-returned x's. */
  Vec Ax, r;
  PetscCall(VecDuplicate(b, &Ax));
  PetscCall(VecDuplicate(b, &r));
  PetscReal ext1, ext2;
  PetscCall(MatMult(A, x1, Ax));
  PetscCall(VecWAXPY(r, -1.0, Ax, b));
  PetscCall(VecNorm(r, NORM_2, &ext1));
  PetscCall(MatMult(A, x2, Ax));
  PetscCall(VecWAXPY(r, -1.0, Ax, b));
  PetscCall(VecNorm(r, NORM_2, &ext2));

  PetscCall(VecCopy(x1, r));
  PetscCall(VecAXPY(r, -1.0, x2));
  PetscReal dx_norm;
  PetscCall(VecNorm(r, NORM_2, &dx_norm));

  if (rank == 0) {
    printf("[multisolve-rng] solve 1: reason=%d rnorm=%.6e ext_res=%.6e\n",
           (int)r1, (double)rn1, (double)ext1);
    printf("[multisolve-rng] solve 2: reason=%d rnorm=%.6e ext_res=%.6e\n",
           (int)r2, (double)rn2, (double)ext2);
    printf("[multisolve-rng] ||x1 - x2||_2 = %.6e (must be 0 exactly)\n", (double)dx_norm);

    int g_reason     = (r1 == KSP_CONVERGED_ATOL && r2 == KSP_CONVERGED_ATOL);
    int g_rnorm      = (rn1 == rn2);
    int g_ext        = ((double)ext1 <= FINAL_RES_FUDGE * TOLABS &&
                        (double)ext2 <= FINAL_RES_FUDGE * TOLABS);
    int g_xidentical = (dx_norm == 0.0);

    printf("[multisolve-rng]   gate reason both=ATOL : -> %s\n", g_reason ? "PASS" : "FAIL");
    printf("[multisolve-rng]   gate rnorm match      : %.6e == %.6e -> %s\n",
           (double)rn1, (double)rn2, g_rnorm ? "PASS" : "FAIL");
    printf("[multisolve-rng]   gate ext residual sane: ext1=%.3e ext2=%.3e (need <= %.3e) -> %s\n",
           (double)ext1, (double)ext2, FINAL_RES_FUDGE * TOLABS, g_ext ? "PASS" : "FAIL");
    printf("[multisolve-rng]   gate x1 == x2 bit-eq  : ||x1 - x2||_2 = %.3e (need 0) -> %s\n",
           (double)dx_norm, g_xidentical ? "PASS" : "FAIL");

    int pass = (g_reason && g_rnorm && g_ext && g_xidentical) ? 1 : 0;
    printf("[multisolve-rng] %s\n", pass ? "[PASS]" : "[FAIL]");

    PetscCallMPI(MPI_Bcast(&pass, 1, MPI_INT, 0, PETSC_COMM_WORLD));
    PetscCall(VecDestroy(&Ax));
    PetscCall(VecDestroy(&r));
    PetscCall(VecDestroy(&x1));
    PetscCall(VecDestroy(&x2));
    PetscCall(VecDestroy(&b));
    PetscCall(MatDestroy(&A));
    PetscCall(KSPDestroy(&ksp));
    PetscCall(PetscFinalize());
    return pass ? 0 : 1;
  }
  int pass_recv = 1;
  PetscCallMPI(MPI_Bcast(&pass_recv, 1, MPI_INT, 0, PETSC_COMM_WORLD));
  PetscCall(VecDestroy(&Ax));
  PetscCall(VecDestroy(&r));
  PetscCall(VecDestroy(&x1));
  PetscCall(VecDestroy(&x2));
  PetscCall(VecDestroy(&b));
  PetscCall(MatDestroy(&A));
  PetscCall(KSPDestroy(&ksp));
  PetscCall(PetscFinalize());
  return pass_recv ? 0 : 1;
}
