/*
   Phase 3b validator (skeleton) — runs KSPGMSTAB with
   `-ksp_gmstab_force_l2_only`, so the driver does exactly one Cycle2
   after Initialisation, then exits. Diffs the resulting trace CSV
   against `cpp_residuals_force_l2.csv` (a fixture generated by the
   C++ port with `GMSTAB_FORCE_L2=1`).

   STATUS: SKELETON. The PETSc-side `force_l2_only` knob and
   `KSPGMSTABCycle2_Private` do NOT yet exist — this validator is
   pre-positioned so that:
     1. The C++ reference baseline is locked in *before* PETSc cycle 2
        is implemented (avoids implementing-test-and-code-together
        sharing the same bug).
     2. As cycle 2 implementation begins, this validator will start
        producing meaningful diff signal (rather than scaffolding
        noise) — every check it does is the same as ex_gmstab_cycle1.

   Until cycle 2 is implemented, expected outcome: FAIL with
   rows_compared=2 (only Init's snapshots are emitted; the cycle-2
   path returns KSP_DIVERGED_BREAKDOWN via the Phase 3a stub).

   Build / run mirror ex_gmstab_cycle1.c exactly.
*/

#include <petscksp.h>
#include <stdio.h>
#include <string.h>
#include <math.h>

#define LINSYS "/home/sam/hpc_stack/gmstab_matlab/gmstab_handoff_package_validation/baselines/cdr_small/linsys.bin"
#define PBIN   "/home/sam/hpc_stack/gmstab_matlab/gmstab_handoff_package_validation/baselines/cdr_small/P.bin"
#define REF    "/home/sam/hpc_stack/gmstab_matlab/gmstab_handoff_package_validation/baselines/cdr_small/cpp_residuals_force_l2.csv"
#define OUT    "/tmp/petsc_cycle2_residuals.csv"

#define DRIFT_TOL_SEQ 1e-10
#define DRIFT_TOL_PAR 1e-7

static PetscErrorCode load_linsys_parallel(MPI_Comm comm, const char *path, Mat *A_out, Vec *b_out)
{
  FILE *fp = fopen(path, "rb");
  PetscFunctionBegin;
  PetscCheck(fp, comm, PETSC_ERR_FILE_OPEN, "Cannot open %s", path);
  char magic[8];
  fread(magic, 1, 8, fp);
  PetscCheck(memcmp(magic, "EXASIMLS", 8) == 0, comm, PETSC_ERR_FILE_READ, "magic");
  int version, idx_size, val_size, reserved;
  fread(&version, sizeof(int), 1, fp); fread(&idx_size, sizeof(int), 1, fp);
  fread(&val_size, sizeof(int), 1, fp); fread(&reserved, sizeof(int), 1, fp);
  unsigned long long N_u, nnz_u;
  fread(&N_u, 8, 1, fp); fread(&nnz_u, 8, 1, fp);
  fseek(fp, 64, SEEK_SET);
  const PetscInt N   = (PetscInt)N_u;
  const PetscInt nnz = (PetscInt)nnz_u;
  PetscCheck(idx_size == 4, comm, PETSC_ERR_FILE_READ, "idx_size != 4");
  int *ai = (int *)malloc(sizeof(int) * (N + 1));
  int *aj = (int *)malloc(sizeof(int) * nnz);
  double *vals = (double *)malloc(sizeof(double) * nnz);
  double *b_arr = (double *)malloc(sizeof(double) * N);
  fread(ai, sizeof(int), N + 1, fp); fread(aj, sizeof(int), nnz, fp);
  fread(vals, sizeof(double), nnz, fp); fread(b_arr, sizeof(double), N, fp);
  fclose(fp);
  Mat A;
  PetscCall(MatCreate(comm, &A));
  PetscCall(MatSetType(A, MATAIJ));
  PetscCall(MatSetSizes(A, PETSC_DECIDE, PETSC_DECIDE, N, N));
  PetscCall(MatSetFromOptions(A));
  PetscInt rstart, rend;
  PetscCall(MatGetOwnershipRange(A, &rstart, &rend));
  PetscInt *d_nnz = (PetscInt *)calloc(rend - rstart, sizeof(PetscInt));
  PetscInt *o_nnz = (PetscInt *)calloc(rend - rstart, sizeof(PetscInt));
  for (PetscInt i = rstart; i < rend; ++i) {
    int rs = ai[i], re = ai[i + 1];
    for (int kk = rs; kk < re; ++kk) {
      if (aj[kk] >= rstart && aj[kk] < rend) d_nnz[i - rstart]++;
      else                                    o_nnz[i - rstart]++;
    }
  }
  PetscCall(MatSeqAIJSetPreallocation(A, 0, d_nnz));
  PetscCall(MatMPIAIJSetPreallocation(A, 0, d_nnz, 0, o_nnz));
  free(d_nnz); free(o_nnz);
  PetscCall(MatSetOption(A, MAT_NEW_NONZERO_ALLOCATION_ERR, PETSC_FALSE));
  for (PetscInt i = rstart; i < rend; ++i) {
    int rs = ai[i], re = ai[i + 1];
    for (int kk = rs; kk < re; ++kk)
      PetscCall(MatSetValue(A, i, aj[kk], vals[kk], INSERT_VALUES));
  }
  PetscCall(MatAssemblyBegin(A, MAT_FINAL_ASSEMBLY));
  PetscCall(MatAssemblyEnd(A,   MAT_FINAL_ASSEMBLY));
  Vec b;
  PetscCall(VecCreate(comm, &b));
  PetscCall(VecSetType(b, VECMPI));
  PetscCall(VecSetSizes(b, PETSC_DECIDE, N));
  PetscCall(VecSetFromOptions(b));
  for (PetscInt i = rstart; i < rend; ++i)
    PetscCall(VecSetValue(b, i, (PetscScalar)b_arr[i], INSERT_VALUES));
  PetscCall(VecAssemblyBegin(b));
  PetscCall(VecAssemblyEnd(b));
  free(ai); free(aj); free(vals); free(b_arr);
  *A_out = A; *b_out = b;
  PetscFunctionReturn(PETSC_SUCCESS);
}

int main(int argc, char **argv)
{
  PetscFunctionBeginUser;
  PetscCall(PetscInitialize(&argc, &argv, NULL, "Phase 3b Cycle2 validator (skeleton)"));

  PetscMPIInt rank, size;
  PetscCallMPI(MPI_Comm_rank(PETSC_COMM_WORLD, &rank));
  PetscCallMPI(MPI_Comm_size(PETSC_COMM_WORLD, &size));

  Mat A; Vec b;
  PetscCall(load_linsys_parallel(PETSC_COMM_WORLD, LINSYS, &A, &b));
  PetscInt N;
  PetscCall(MatGetSize(A, &N, NULL));
  if (rank == 0) printf("[cycle2] loaded cdr_small: N=%" PetscInt_FMT " on %d ranks\n", N, (int)size);

  Vec x;
  PetscCall(VecDuplicate(b, &x));
  PetscCall(VecSet(x, 0.0));

  KSP ksp;
  PetscCall(KSPCreate(PETSC_COMM_WORLD, &ksp));
  PetscCall(KSPSetOperators(ksp, A, A));
  PetscCall(KSPSetType(ksp, KSPGMSTAB));
  PetscCall(KSPSetTolerances(ksp, 0.0, 1e-10, PETSC_DEFAULT, 500));
  PetscCall(KSPSetNormType(ksp, KSP_NORM_UNPRECONDITIONED));
  PC pc;
  PetscCall(KSPGetPC(ksp, &pc));
  PetscCall(PCSetType(pc, PCNONE));

  PetscCall(PetscOptionsSetValue(NULL, "-ksp_gmstab_s",              "4"));
  PetscCall(PetscOptionsSetValue(NULL, "-ksp_gmstab_p_file",         PBIN));
  if (rank == 0) {
    PetscCall(PetscOptionsSetValue(NULL, "-ksp_gmstab_trace_csv", OUT));
  }
  /* This option does not yet exist in PETSc — the validator is a
     skeleton until KSPGMSTABCycle2_Private and the force_l2_only knob
     are implemented. PetscOptionsSetValue accepts the unknown key
     silently; PetscOptionsBool inside SetFromOptions will simply not
     find it, and gms->force_l2_only stays PETSC_FALSE. */
  PetscCall(PetscOptionsSetValue(NULL, "-ksp_gmstab_force_l2_only", "true"));
  PetscCall(KSPSetFromOptions(ksp));

  PetscCall(KSPSolve(ksp, b, x));

  KSPConvergedReason reason;
  PetscCall(KSPGetConvergedReason(ksp, &reason));
  if (rank == 0) printf("[cycle2] KSPSolve returned reason=%d\n", (int)reason);

  PetscCall(VecDestroy(&x));
  PetscCall(VecDestroy(&b));
  PetscCall(MatDestroy(&A));
  PetscCall(KSPDestroy(&ksp));

  int pass = 1;
  if (rank == 0) {
    FILE *ours = fopen(OUT, "r");
    FILE *ref  = fopen(REF, "r");
    if (!ours || !ref) {
      printf("[cycle2] cannot open files for comparison\n");
      pass = 0;
    } else {
      char buf_o[1024], buf_r[1024];
      fgets(buf_o, sizeof(buf_o), ours);
      fgets(buf_r, sizeof(buf_r), ref);

      const double drift_tol = (size == 1) ? DRIFT_TOL_SEQ : DRIFT_TOL_PAR;
      printf("[cycle2] mode=%s drift_tol=%.0e\n",
             (size == 1) ? "sequential" : "parallel", drift_tol);

      int rows_compared    = 0;
      int matvec_match_all = 1;
      int first_mismatch   = -1;
      double max_iter_drift = 0.0, max_true_drift = 0.0;
      while (fgets(buf_o, sizeof(buf_o), ours)) {
        if (!fgets(buf_r, sizeof(buf_r), ref)) break;
        int io, mo;  double iro, tro, ru_o, rmv_o;
        int ir_, mr; double irr, trr, ru_r, rmv_r;
        sscanf(buf_o, "%d,%d,%lf,%lf,%lf,%lf", &io, &mo, &iro, &tro, &ru_o, &rmv_o);
        sscanf(buf_r, "%d,%d,%lf,%lf,%lf,%lf", &ir_, &mr, &irr, &trr, &ru_r, &rmv_r);
        int match = (mo == mr) ? 1 : 0;
        if (!match) matvec_match_all = 0;
        double dr_iter = fabs(iro - irr);
        double dr_true = fabs(tro - trr);
        if (dr_iter > max_iter_drift) max_iter_drift = dr_iter;
        if (dr_true > max_true_drift) max_true_drift = dr_true;
        int row_pass = (match && dr_iter < drift_tol && dr_true < drift_tol);
        if (!row_pass && first_mismatch < 0) first_mismatch = rows_compared;
        printf("[cycle2] row %2d: ours=(mv=%d, iter=%.6e, true=%.6e)  ref=(mv=%d, iter=%.6e, true=%.6e)  drift=%.2e/%.2e  %s\n",
               rows_compared, mo, iro, tro, mr, irr, trr, dr_iter, dr_true,
               row_pass ? "ok" : "MISMATCH");
        rows_compared++;
      }
      fclose(ours);
      fclose(ref);

      printf("[cycle2] rows_compared=%d matvec_match_all=%d max_iter_drift=%.3e max_true_drift=%.3e first_mismatch=%d\n",
             rows_compared, matvec_match_all, max_iter_drift, max_true_drift, first_mismatch);
      /* For cycle 2, the C++ reference has many more rows than cycle 1
         (the post-aug-gmres snapshots, plus the post-update). Until
         cycle 2 is implemented, rows_compared will be 2 (just Init).
         Once it's implemented and force_l2_only is plumbed in, the
         expected count is comparable to cycle 1's 11 (begin-cycle +
         a stream of inner-pgmres-style snapshots from aug_gmres_m +
         the final cycle snapshot). The ≥10 floor is the same as
         cycle 1's. */
      pass = (rows_compared >= 10 && matvec_match_all
              && max_iter_drift < drift_tol && max_true_drift < drift_tol) ? 1 : 0;
      printf("[cycle2] %s\n", pass ? "[PASS]" : "[FAIL — expected until cycle 2 is implemented]");
    }
  }
  PetscCallMPI(MPI_Bcast(&pass, 1, MPI_INT, 0, PETSC_COMM_WORLD));

  PetscCall(PetscFinalize());
  return pass ? 0 : 1;
}
